### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by PBWiseman**
Changelog
-
- ADD:  Game Tutorial
- ADD: Quit Shortcut
- ADD:  Temporary Partical Visuals
- REMOVE: (TBD)

Bug fixes
-
- FIX: Render Texture Fix 
- FIX: Windmill Trigger Bug

Known bugs
- 
- BUG: (TBD)

Background Improvements
-
- IMPROVE: (TBD)

### CODE REVIEW

**Comment by PBWiseman** [comment]
Looks all good

**Review by ChaseBENNC9 — APPROVED** [review]
good

**Review by LiamMcKenzie — APPROVED** [review]
Looks good to me

**Review by Carlson-Lee — APPROVED** [review]
All feature seems good.

**Pull request merged**
