### PR TITLE
v1.4.0

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
Changelog
-
- ADD: Score System functional with both Wind and Solar power 
- ADD: End of level menu
- ADD: Level 1
- ADD: Tutorial Narrative
- CHANGE: Updated Title screen and settings menu
- REMOVE: (TBD)

Visuals
-
- VISUAL: New Wire Particles when powered

Bug fixes
-
- FIX: Wire deletion issue

Known bugs
- 
- BUG: (TBD)

Background Improvements
-
- IMPROVE: The Bonus tile type and location can be set in the inspector using struct

### CODE REVIEW

**Review by LiamMcKenzie — APPROVED** [review]
Looks good to me

**Review by PBWiseman — CHANGES_REQUESTED** [review]
The end screen needs to be disabled in the scene as when you click from the main menu it starts activated.
The Next Level button currently points to the "chase" scene. It should probably point to the same "Level1" scene
The power effects on the wires still don't work for anything but the center score tile

**Review by PBWiseman — APPROVED** [review]
Looks good. The tutorial no longer has bonus tiles for the last step but that should be fine.

**Review by Carlson-Lee — APPROVED** [review]
Looks good !

**Pull request merged**
