### PR TITLE
Wind/Solar particle effects

### PR DESCRIPTION
**Pull request by PBWiseman**
## Describe your changes
This branch will add particle effects to show the player what tiles are sunnier or windier to get score from. The sunnier parts should have sun rays and particles with a fade off towards the edges. The windier parts should have gusts of winds blowing through the play area. This should be able to be done programmatically so it can be loaded with the tile data for each level.

## Issue number and link
#76

### CODE REVIEW

**Comment by PBWiseman** [comment]
I ended up giving up on the textures following multiple workshopping sessions with teammates as well as a conversation with the product manager. They advised that I get the code for placing it in and add more temporary visuals. We can then come back to this at a later date when we have better ideas for how it should work

**Review by Carlson-Lee — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Particle effects are not implemented, however a different feature is added.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - The bonus tile score script looks good, it fulfills it's core functionality.

_Any repetitive code that could be refactored? (DRY)_  

 - N/A


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Yes, the code works properly.


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - No notiable performance issue.


# Final Comments

 - Great implementation.

***

**Review by ChaseBENNC9 — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Happy with functionality, temporary visuals are fine for now, the transparency indicates lower strength of sun or wind


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Code is very well written and is formatted nicely

_Any repetitive code that could be refactored? (DRY)_  

 - No


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Code is running fine, no issue with performance

**Review by LiamMcKenzie — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - This is a decent working solution for displaying wind/solar power.
 - I'm aware of how you've tested multiple solutions and I think this is the most functional.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - There are no comments, these would be really helpful.

_Any repetitive code that could be refactored? (DRY)_  

 - the tile materials could have been in a list or array, instead of wind1, wind2, wind3
 - There is also repeated code for the tiles
 - Despite the repeated code, it still functions correctly. The code is otherwise well written.


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - No noticeable bugs


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - No noticeable speed issues


# Final Comments

 - This feature looks great

***

**Pull request merged**
