### PR TITLE
Score Rework + Endgame

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
## Description
Reworking the score to work with both building types and made it easier to generate score tiles in the inspector using structs. I'm also doing temporary visuals for the endgame screen after all the slots in the central have been filled. the user is rated on a 5-Star Scale depending on how well they did (more details below)

## Issue
- #91

### CODE REVIEW

**Comment by ChaseBENNC9** [comment]
Optimal Score
the Adjacent tile score (2) multiplied by the number of open slots on the goal e.g. (8) 
example score 16
once all the slots are filled the end screen will appear?
if the user scored below 16 then the level is counted as fail
anything above 16 is graded on a 5 star scale.
the maximum score will need to be calculated to do this scale
we should have rules on how many score tiles are available in comparison to open goal slots

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Great work with the struct. It looks really good. The X and Y range needs to be 0-9. Can the adjacent and diagonals lists be hide in inspector as well so it is less cluttered? Can the .vscode folder also please be in gitignore. Happy for it to be merged when these are fixed. Great code!

**Review by LiamMcKenzie — APPROVED** [review]
Looks good to merge.
The code in GridManager.cs is really well written. I like the look of the end screen.
The blue for wind could be lighter but I think it does the job

**Review by PBWiseman — APPROVED** [review]
Looks great! All requested changes made.

**Review by Carlson-Lee — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - Yes, the calculation for this is very crucial for the core game play !


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Very well written

_Any repetitive code that could be refactored? (DRY)_  

 - No.


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - The calculation in the game scene looks great, checking power generation and wind generation separately, and correctly.


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - Colour for the wind tile can could be different, since blue does not suit the overall colour of the game and it's making the blue standout in comparison to the orange tile.


# Final Comments

 - Great implementation overall !!

***

**Pull request merged**
