### PR TITLE
Game Tutorial

### PR DESCRIPTION
**Pull request by ChaseBENNC9**
## Describe your changes

Creating a tutorial for the game, this should introduce the player to the game and all of the mechanics, There would be a starting level to introduce all these things and it would in someway be marked as the tutorial level

1.   **Tutorial for placing a building**
- Tooltip appears: "Start by placing the windmill on the highlighted tile"
- the building button is highlighted and the target tile will remain orange.   
**(Building can only be placed here for now)**
- [x] DONE

2. **Wiring Buildings to center**
- The tool tip updates: "Click on the windmill to start wiring, Follow the highlighted path to the central building"
- tiles will be highlighted slightly. the user can follow them with the mouse to place each wire until they reach the central building
- [x] DONE
3. **Delete Mode**
- The Tooltip updates "Use Delete Mode to remove these buildings and return them to your inventory.
The player deletes the buildings"
- Next Section Button? 
- The Scene changes, a windmill and a solar panel are on the grid, the delete mode button highlights
- [x] DONE
5. **Obstacles**. 
- The Tooltip updates "Wires cannot go through certain obstacles. Try and place your buildings and wire them to the power source while avoiding them"
- [x] DONE
6. **Completion**
- [x] DONE
**Other**
- Several tooltips are on objects of interest these can be clicked to show more information.
- [x] allow the user to expand the tooltips for items of interest

## Issue number and link
#62

### CODE REVIEW

**Review by PBWiseman — CHANGES_REQUESTED** [review]
Excellent code and feature! Just a couple of small bugs:

- If buildings are deleted after the tutorial has finished the tooltips start breaking

- Capitalization. The first you should be lowercase and the second should be capitalized 
image

- Not really a bug but when you need to place the two buildings, I didn't notice that it gave you one more of each. Something to make this a little more obvious would be good.

- Adding new points tiles for the second set of buildings to reinforce that you should be trying to score points with them would probably be good.

- There are two spaces between have and active here
image

- Tutorial probably shouldn't be capitalized here 
image

- Last thing is just having a way of getting into it and then getting on to the first level

I love the functionality though and it will be great for teaching people the game!

**Comment by ChaseBENNC9** [comment]
should have resolved all issues

**Review by LiamMcKenzie — CHANGES_REQUESTED** [review]
### Changes requested
- Some of the popup boxes have text that goes off screen.
- The popup boxes also feel hard to notice, and if these were forced info boxes this might be better
Tutorial Bug 1
- If i stop dragging a wire during the tutorial, some of the highlighted tiles will remain
Tutorial Bug 2

- The last part of the tutorial where it tells you to place down new buildings could use a change. It should have highlighted tiles to force the player to move around objects
# Overview
Other than the requested changes I really like this tutorial. The code is all very well written.

**Comment by ChaseBENNC9** [comment]
as discussed i've slightly moved down the central building  popup and made the toggle alternate between + and x

**Review by LiamMcKenzie — APPROVED** [review]
The changes I've requested have been addressed. Looks good to merge into staging

**Review by PBWiseman — APPROVED** [review]
The tutorial still needs to be added to the build settings to load from the main menu.
The only other feedback I have is that it was a little confusing to have multiple tiles that look highlighted when told to place on a highlighted. This might not be a major problem as a tile is very obviously highlighted when they actually do click on the building. The tutorial works great overall though. Well done!

**Review by Carlson-Lee — APPROVED** [review]
# Code Review

## Functional Requirements
_Is the application fit for purpose? Does it meet the user’s requirements and properly address the issue?_  

 - The tutorial is very crucial for this game, and it's implemented properly.


## Legibility and Style
_Uses agreed coding standards/conventions? Readable, consistent and well-structured with useful comments?_  

 - Code is very consistent and readable.

_Any repetitive code that could be refactored? (DRY)_  

 - Not noticeable.


## Correctness of the Code
_Is the code reliable, giving same results every time it runs? Does it function correctly?_  

 - Yes, the functionality is working properly.


## Implementation
_Any notable performance/speed issues? Compatibility and Responsiveness on other platforms ?_  

 - None noticeable


# Final Comments

 - Great work overall, there is a small issue with t in tutorial is not capitalized. image

***

**Pull request merged**
